The Recipe file
===============
Stefan Suciu <stefan@s2i2.ro>
1.0, 2015-02-04
:toc:
:icons: font
:quick-uri: http://s2i2.ro/projects/app-transfer/

WARNING: This is work in progres...

== The header (recipe) section

```
<recipe>
  version               = 1
  syntaxversion         = 1
  name                  = Test recipe
  description           = Does this and that...
</recipe>
```

=== The Header Attributes

version       :: The version of the recipe.  Not managed by the application.
syntaxversion :: The version of the recipe syntax.  The current recipe format value is 1.
name          :: The name of the recipe.
description   :: A description of the recipe.
table         :: The destination table name.


== The config section

An example for a complete file =to=> database transfer recipe config
section:

```
<config>
  <source>
    reader        = excel
    file          = siruta.xls
  </source>

  <destination>
    writer        = db
    target        = siruta
    table         = siruta
  </destination>
</config>
```

The file, target and table attributes are optional in the recipe files
but must be provided from the application configuration or from the
CLI options.

=== The config Attributes

reader        :: The reader module name.  The implemented modules are: *excel*, *csv* and *db*.
writer        :: The writer module name:  The implemented modules are: *db*.

In the *App::Transfer* recipe file:

The target configuration is like this:

```
<target siruta>
  uri           = db:firebird://user:pass@localhost//home/fbdb/siruta.fdb
</target>
```

Alternatively, in the *App::Transfer* configuration files (transfer.conf):

```
[target "siruta"]
        uri = db:firebird://user:pass@localhost//home/fbdb/siruta.fdb
```
